### ISSUE TITLE
"Unknown directive" reported for valid abbreviations for IP-related directives

### ISSUE THREAD

**Issue by seththeriault** [cu-library/ezproxy-config-lint#10]
Each of the following abbreviations are being reported as an "Unknown directive":

`A` ([`AutoLoginIP`](https://help.oclc.org/Library_Management/EZproxy/Configure_resources/AutoLoginIP))
`E` ([`ExcludeIP`](https://help.oclc.org/Library_Management/EZproxy/Configure_resources/ExcludeIP))
`I` ([`IncludeIP`](https://help.oclc.org/Library_Management/EZproxy/Configure_resources/IncludeIP))

These abbreviations are explicitly mentioned in the documentation .

**Comment by cudevmaxwell** [comment]
Thanks for the issue @seththeriault! Oversight on my part. Can you try release v0.0.5? Should be fixed with https://github.com/cu-library/ezproxy-config-lint/commit/b7cf558da9b29117ba5c9f2286b8f6e206e74b36

**Comment by seththeriault** [comment]
@cudevmaxwell, I tested with v0.0.5 and it's fixed.

**Comment by cudevmaxwell** [comment]
Fantastic, thanks @seththeriault!
