### ISSUE TITLE
Print file path in output

### ISSUE THREAD

**Issue by moorereason** [cu-library/ezproxy-config-lint#12]
### Current behavior

```
$ ezproxy-config-lint ./databases/a*.txt
2: URL http://www.humanitiesebook.org/ !!! URL is not using HTTPS scheme
2: URL http://www.asha.org/publications/ !!! URL is not using HTTPS scheme
```

It's really noticeable when passing multiple files on the cli.

### Proposal
My suggestion is to follow standard linter practice that's described by the _Text_ format of [staticcheck](https://staticcheck.dev/docs/running-staticcheck/cli/formatters/).

```
file:line:col: message
```

The linter doesn't currently support column identification, so that may could be added later.

### Example

```
$ ezproxy-config-lint ./databases/a*.txt
./databases/oclc/acls_humanities.txt:2: URL http://www.humanitiesebook.org/ !!! URL is not using HTTPS scheme
./databases/oclc/asha.txt:2: URL http://www.asha.org/publications/ !!! URL is not using HTTPS scheme
```

**Comment by cudevmaxwell** [comment]
@moorereason With 5420098430819e35630365a8305a30ef6e08f036 this and issue #2 should be fixed. If possible, would you be able to test out [ v0.0.7  ](https://github.com/cu-library/ezproxy-config-lint/releases/tag/v0.0.7) and see what you think? Thanks!

**Comment by moorereason** [comment]
Resolved.  Thanks
