### ISSUE TITLE
Recognize comment character (#) as stanza separator to avoid false positives

### ISSUE THREAD

**Issue by seththeriault** [cu-library/ezproxy-config-lint#14]
At the moment, only a blank/whitespace line is recognized as a stanza separator:

```
$ cat test.txt 
Title Google
URL https://google.com

Title Yahoo
URL https://yahoo.com
$ ./ezproxy-config-lint test.txt
$
```

Non-blank lines beginning with comment characters (#) generate error messages:

```
$ cat test.txt 
Title Google
URL https://google.com
#
Title Yahoo
URL https://yahoo.com
$ ./ezproxy-config-lint test.txt 
4: Title Yahoo !!! Duplicate Title directive, Title directive is out of order
5: URL https://yahoo.com !!! Duplicate URL directive
```

**Comment by cudevmaxwell** [comment]
In the [0.0.8](https://github.com/cu-library/ezproxy-config-lint/releases/tag/v0.0.8) release, I've changed the definition of an empty line to be an empty comment (`=="#"`) or an empty line. I'm personally not 100% sold that the linter should accept empty comments as stanza separators, but that's just an aesthetic preference on my part.
