### ISSUE TITLE
Disable HTTPS check by default

### ISSUE THREAD

**Issue by seththeriault** [cu-library/ezproxy-config-lint#15]
Since non-secure URLs are still valid, the HTTPS check generates numerous information messages.

It should be disabled by default and enabled behind a flag.

**Comment by cudevmaxwell** [comment]
Ha! Just fixed in 6a13e95290c3d706dfd8afdfd5ea00309c11ff81, can you try [v0.0.7](https://github.com/cu-library/ezproxy-config-lint/releases/tag/v0.0.7)?

**Comment by seththeriault** [comment]
Definitely working in v0.0.7.
