### ISSUE TITLE
Previous titles & origins hints are inaccurate when previous entry is from an included file

### ISSUE THREAD

**Issue by moorereason** [cu-library/ezproxy-config-lint#19]
A contrived example (hopefully, my error messages are accurate).

Given config.txt:
```text
IncludeFile sample.txt

# Blah
Title Foo
URL sample.com
Host www.sample.org
```

Given sample.txt:
```
Title Sample
URL sample.com
Host www.sample.org
```

Linter output:
```
config.txt:6: Host www.sample.org ← Origin already seen on line 3
```

If the line is from another file, I would expect it to reference that file:
```
config.txt:6: Host www.sample.org ← Origin already seen at sample.txt:3
```

**Comment by cudevmaxwell** [comment]
Good catch @moorereason. This was one of those bugs where the fix involved some nice simplification: https://github.com/cu-library/ezproxy-config-lint/compare/v0.0.16...v0.0.18 
Ready to test in v0.0.18.
