### ISSUE TITLE
Follow IncludeFile paths

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/ezproxy-config-lint#2]
Have to tool check IncludeFile paths as well as files provided as arguments.

**Comment by seththeriault** [comment]
In v0.0.7, the tool is only checking IncludeFile paths relative to the current directory:

```
$ ls test.txt test-includes
test.txt

test-includes:
test-include.txt

$ cat test.txt
Title Google
URL https://google.com

Title Yahoo
URL https://yahoo.com

IncludeFile test-includes/test-include.txt
$ cat test-includes/test-include.txt
Title Bing
URL https://bing.com

$ ./ezproxy-config-lint_Linux_x86_64-0.0.7/ezproxy-config-lint -annotate test.txt 
test.txt:1: Title Google
test.txt:2: URL https://google.com
test.txt:3: 
test.txt:4: Title Yahoo
test.txt:5: URL https://yahoo.com
test.txt:6: 
test.txt:7: IncludeFile test-includes/test-include.txt
test-includes/test-include.txt:1: Title Bing
test-includes/test-include.txt:2: URL https://bing.com
```
But not the one in which the config.txt file is located:

```
$ cd ezproxy-config-lint_Linux_x86_64-0.0.7
$ ls 
ezproxy-config-lint  LICENSE.md  README.md
$ ./ezproxy-config-lint -annotate ../test.txt 
../test.txt:1: Title Google
../test.txt:2: URL https://google.com
../test.txt:3: 
../test.txt:4: Title Yahoo
../test.txt:5: URL https://yahoo.com
../test.txt:6: 
../test.txt:7: IncludeFile test-includes/test-include.txt
Error encountered when processing line "IncludeFile test-includes/test-include.txt".
test-includes/test-include.txt resolves to the absolute path /tmp/ezproxy-linter/ezproxy-config-lint_Linux_x86_64-0.0.7/test-includes/test-include.txt.
Error processing ../test.txt: open test-includes/test-include.txt: no such file or directory
```

**Comment by cudevmaxwell** [comment]
Try the ` -include-file-directory` parameter. If the `IncludeFile` path isn't absolute, the linter will first join the provided path to the paths in the config file. 

In your example, I think the command would be `./ezproxy-config-lint -include-file-directory .. -annotate ../test.txt`.

Appreciate the feedback and the detailed issues.

**Comment by cudevmaxwell** [comment]
@seththeriault You were right, it didn't make a lot of sense to look in the current working directory for `IncludeFile` paths. In [0.0.9](https://github.com/cu-library/ezproxy-config-lint/releases/tag/v0.0.9), the linter joins the config file's directory with the `IncludeFile` path, unless the path is absolute in the config file or the `-include-file-directory` parameter is used.
