### ISSUE TITLE
Handle a multiline `ShibbolethMetadata` directive

### ISSUE THREAD

**Issue by moorereason** [cu-library/ezproxy-config-lint#8]
Two items that need to be supported:

1. the `ShibbolethMetadata` directive
1. multiline statements

See the [SAML Authentication documentation](https://help.oclc.org/Library_Management/EZproxy/Authenticate_users/EZproxy_authentication_methods/SAML_authentication):

```
ShibbolethMetadata \
   -EntityID=EZproxyEntityID \
   -File=MetadataFile \
   -SignResponse=false -SignAssertion=true -EncryptAssertion=false \
   [-Cert=EZproxyCertNumber \]
   [-SignAuthnRequest \]
   [-SLO \]
   [-URL=MetadataURL \]
   [-URLValidate=URLValidateFile \]
   [-AuthnContextClassRef=AuthnContext]
```

**Comment by cudevmaxwell** [comment]
Thanks for the issue @moorereason! I've added initial support for both the ShibbolethMetadata  directive and multiline strings more generally in https://github.com/cu-library/ezproxy-config-lint/commit/09effe1c86d03cff454a6f0e5b18d0a242fe249a Can you try release v0.0.3?

**Comment by moorereason** [comment]
Resolved.

PS - Great job with this tool.  I've been programming in Go as a hobby for years and was honestly surprised to see such good work pop up on the ezproxy community list.  Kudos!  🏆
