### ISSUE TITLE
Support special Ebrary option and directive

### ISSUE THREAD

**Issue by moorereason** [cu-library/ezproxy-config-lint#9]
See [Ebrary stanza](https://help.oclc.org/Library_Management/EZproxy/EZproxy_database_stanzas/Database_stanzas_E/Ebrary) for `ebraryUnencodedTokens` option and `ebrarySite` directive.  Also used in [Ebook Central](https://help.oclc.org/Library_Management/EZproxy/EZproxy_database_stanzas/Database_stanzas_E/Ebook_Central).

```
Option ebraryUnencodedTokens
Title ebrary (Added 20230829)
ebrarySite [sitename]
Host site.ebrary.com
URL http://site.ebrary.com/lib/[sitename]
Neverproxy *.ebrary.com
```

**Comment by cudevmaxwell** [comment]
I've added support for  `ebrarySite` and `Option ebraryUnencodedTokens` to the latest release. Can you test v0.0.4?

**Comment by moorereason** [comment]
Resolved.
